#!/usr/bin/env python3
"""
Convert scrape_doc.py output into supabase/seed_catalog.sql.

    python3 scripts/scrape_doc.py --term Fall2026 --subjects COMS,MATH --out data/
    python3 scripts/catalog_to_sql.py data/courses_20263.json data/sections_20263.json

Idempotent: courses upsert on (term, code), sections on (course_id, section).
"""

import json
import pathlib
import sys


def q(v):
    if v is None:
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    courses = json.load(open(sys.argv[1]))
    sections = json.load(open(sys.argv[2]))

    out = [
        "-- Generated by scripts/catalog_to_sql.py -- do not edit by hand.",
        f"-- {len(courses)} courses, {len(sections)} sections.",
        "",
    ]
    for c in courses:
        out.append(
            "insert into public.courses (term, code, subject, number, title, department) "
            f"values ({q(c['term'])}, {q(c['code'])}, {q(c['subject'])}, {q(c['number'])}, "
            f"{q(c['title'])}, {q(c.get('department'))}) "
            "on conflict (term, code) do update set title = excluded.title;"
        )
    out.append("")
    for s in sections:
        enrolled = s.get("enrolled") if s.get("enrolled") is not None else "null"
        capacity = s.get("capacity") if s.get("capacity") is not None else "null"
        out.append(
            "insert into public.sections (course_id, term, section, call_number, "
            "instructor, points, enrolled, capacity, legacy_number) "
            f"select id, {q(s['term'])}, {q(s['section'])}, {q(s.get('call_number'))}, "
            f"{q(s.get('instructor'))}, {q(s.get('points'))}, {enrolled}, {capacity}, "
            f"{q(s.get('legacy_number'))} "
            f"from public.courses where term = {q(s['term'])} and code = {q(s['code'])} "
            "on conflict (course_id, section) do update set "
            "call_number = excluded.call_number, instructor = excluded.instructor, "
            "enrolled = excluded.enrolled, capacity = excluded.capacity;"
        )

    dest = pathlib.Path(__file__).resolve().parent.parent / "supabase" / "seed_catalog.sql"
    dest.write_text("\n".join(out) + "\n")
    print(f"{len(courses)} courses, {len(sections)} sections -> {dest}")


if __name__ == "__main__":
    main()
